# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [23]:
import pandas as pd
df_mca = pd.read_csv("../lab-dw-data-structuring-and-combining/df_mca_save")
display(df_mca.head())

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809,No,Basic,College,2011-02-18,Employed,M,48029,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292,Four-Door Car,Medsize,A,2
1,KX64629,California,2228,No,Basic,College,2011-01-18,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744,Four-Door Car,Medsize,A,1
2,LZ68649,Washington,14947,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,2,Personal Auto,Personal L3,Offer3,Call Center,480,SUV,Medsize,A,2
3,XL78013,Oregon,22332,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484,Four-Door Car,Medsize,A,1
4,QA50777,Oregon,9025,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,7,Personal Auto,Personal L2,Offer1,Branch,707,Four-Door Car,Medsize,A,1

In [24]:
df_customer = df_mca.loc[(df_mca["response"] == "Yes") & (df_mca["total_claim_amount"] < 1000)]
df_customer = df_customer.reset_index(drop = True)
display(df_customer)

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,XL78013,Oregon,22332,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484,Four-Door Car,Medsize,A,1
1,FM55990,California,5989,Yes,Premium,College,2011-01-19,Employed,M,66839,...,1,Personal Auto,Personal L1,Offer2,Branch,739,Sports Car,Medsize,A,1
2,CW49887,California,4626,Yes,Basic,Master,2011-01-16,Employed,F,79487,...,1,Special Auto,Special L1,Offer2,Branch,547,SUV,Medsize,A,1
3,NJ54277,California,3746,Yes,Extended,College,2011-02-26,Employed,F,41479,...,1,Personal Auto,Personal L2,Offer2,Call Center,19,Two-Door Car,Large,A,2
4,MQ68407,Oregon,4376,Yes,Premium,Bachelor,2011-02-28,Employed,F,63774,...,1,Personal Auto,Personal L3,Offer2,Agent,60,Four-Door Car,Medsize,A,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,FM31768,Arizona,5979,Yes,Extended,High School or Below,2011-02-07,Employed,F,57693,...,3,Personal Auto,Personal L1,Offer2,Agent,547,Four-Door Car,Medsize,A,2
1395,KZ80424,Washington,8382,Yes,Basic,Bachelor,2011-01-27,Employed,M,25998,...,2,Personal Auto,Personal L2,Offer2,Call Center,791,Four-Door Car,Medsize,A,1
1396,XT67997,California,5979,Yes,Extended,High School or Below,2011-02-07,Employed,F,57693,...,3,Personal Auto,Personal L3,Offer2,Agent,547,Four-Door Car,Medsize,A,2
1397,BY78730,Oregon,8879,Yes,Basic,High School or Below,2011-02-03,Employed,F,52583,...,7,Special Auto,Special L2,Offer1,Agent,528,SUV,Small,A,2
1398,MM70762,Arizona,9075,Yes,Basic,Master,2011-01-26,Employed,M,37722,...,8,Personal Auto,Personal L1,Offer1,Agent,158,Sports Car,Medsize,A,1

In [25]:
#to get monthly premium column 
df_mca.columns.tolist()
df_mca["monthly_premium_auto"].head()

0     61
1     64
2    100
3     97
4    117
Name: monthly_premium_auto, dtype: int64

In [68]:
df_summary = (df_mca.loc[df_mca["response"] == "Yes"]
            .groupby(["policy_type","gender"])[["monthly_premium_auto","customer_lifetime_value","total_claim_amount"]]
            .mean())

df_summary["clv_to_claims"] = df_summary["customer_lifetime_value"]/df_summary["total_claim_amount"]

display(df_summary.sort_values(by="clv_to_claims",ascending = False))

#Most profitable or low risk: males with Corporate Auto Policy type
# least profitable or high risk: males with Personal Auto Policy type

,,monthly_premium_auto,customer_lifetime_value,total_claim_amount,clv_to_claims
policy_type,gender,,,,
Corporate Auto,M,92.188312,7943.928571,408.123377,19.464527
Special Auto,M,86.343750,8246.593750,429.125000,19.217230
Personal Auto,F,98.998148,8339.279630,452.498148,18.429423
Corporate Auto,F,94.301775,7712.153846,433.295858,17.798817
Special Auto,F,92.314286,7691.085714,452.857143,16.983470
Personal Auto,M,91.085821,7447.867537,456.576493,16.312420

In [62]:
df_customer_state = df_mca.groupby("state").agg(customer_count = ("customer","size"))
df_maxcustomer_state = df_customer_state.loc[df_customer_state["customer_count"]>500]
display(df_maxcustomer_state)

            customer_count
state
Arizona               1937
California            4183
Nevada                 993
Oregon                2909
Washington             888

In [61]:

#Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.
df_clv = df_mca.groupby(["gender","education"]).agg(
        clv_max = ("customer_lifetime_value","max"),
        clv_min = ("customer_lifetime_value","min"),
        clv_median = ("customer_lifetime_value","median")
)
df_clv

# The median is similar for all groups, ranging from 5332 to 6286
# The highest median for both males and females with lower education, high school or below 
#The lowest median is female doctor and in males have almost similar values for doctor, master, bachelor education
# Some groups have high difference between high and low values
# There is less gender difference in values

                             clv_max  clv_min  clv_median
gender education
F      Bachelor                73225     1904      5640.0
       College                 61850     1898      5623.0
       Doctor                  44856     2395      5332.0
       High School or Below    55277     2144      6039.5
       Master                  51016     2417      5729.0
M      Bachelor                67907     1898      5548.0
       College                 61134     1918      6005.0
       Doctor                  32677     2267      5577.0
       High School or Below    83325     1940      6286.5
       Master                  50568     2272      5578.5